### ISSUE TITLE
Error loading shared lib on system update

### ISSUE THREAD

**Issue by teronslair** [nomeata/arbtt#154]
Hi Joachim,

Thought about posting here instead of an email. Maybe somebody else can benefit from an answer.
I'm a Garuda Linux user that was benefiting from version 0.11.1-1 of arbtt until yesterday.
After a system update I now get: 
`error while loading shared libraries: libHSutf8-string-1.0.2-FOQgGpXm4p2BxMMm2pyYrn-ghc9.0.2.so: cannot open shared object file: No such file or directory`
Checked the libs directory and sure enough I now have another lib version:
```
ls /usr/lib | grep libHS | grep utf8
.rwxr-xr-x  301k root  4 mai 13:02  libHSutf8-string-1.0.2-9eFA57BgKXNHtjvfuIOq9f-ghc9.0.2.so
```
What should I do next? What is the plan in such a situation? Do you plan to offer support with the new library versions? Should I wait for  a new arbtt package release? Do I need to sandbox arbtt and freeze all lib versions in place somehow for it to continue working?

I know it's not a bug per se so sorry in advance for the spam. As i mentioned in the beginning the arbtt resources point to this bug tracker so a lot of folks are likely to end up here for a similar issue.

UPDATE:
In the meantime I'll rebuild from source. But the one thing I cannot figure out is how these libs get these weird hash values in their name and who updates them, cause I didn't update via cabal willingly.

Thank you for your effort,
Razvan

**Comment by nomeata** [comment]
Hi Razvan, Garunda is Arch-based, right?

The problem is likely one on the distribution site of things: It looks like they rebuilt `utf8-string` (hence the changed hash in the filename) without (yet) rebuilding all depending packages. I don’t know how the Arch or Garunda team is managing their Haskell packages, whether fixed will come in eventually or if you should report it. In Debian, we have infrastructure that would have prevented you from installing the new `utf8-string` before the updated `arbtt` is ready.

So maybe ping the Garunda/Arch people for help?

**Comment by teronslair** [comment]
Thanks for the suggestion Joachim. 
Yes, Garuda is an Arch based distro. After a bit more digging I reached the same conclusion as you did. Someone was too trigger happy with the Haskell packages update.
I will follow up with the Garuda team.

Have a nice day!
